<!doctype html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Ingreso</title>
    <link rel="stylesheet" href="/js/sencha/resources/css/sencha-touch.css" type="text/css">
    <script type="text/javascript" src="/js/sencha/sencha-touch.js"></script>
    <script type="text/javascript">
    Ext.setup({
        icon: 'icon.png',
        tabletStartupScreen: 'tablet_startup.png',
        phoneStartupScreen: 'phone_startup.png',
        glossOnIcon: false,
        onReady: function() {

            var form;

            Ext.regModel('User', {
                fields: [
                {
                    name: 'name',
                    type: 'string'
                },

                {
                    name: 'password',
                    type: 'password'
                },
                ]
            });


            var formBase = {
                //scroll: 'vertical',
                url   : '/auth/login/',
                standardSubmit : false,
                items: [{
                    xtype: 'fieldset',
                    title: 'Ingreso',
                    instructions: 'Ingrese su informacion.',
                    defaults: {
                        required: true,
                        labelAlign: 'left',
                        labelWidth: '40%'
                    },

                    items: [
                    {
                        xtype: 'textfield',
                        name : 'login',
                        label: 'Nombre',
                        useClearIcon: true,
                        autoCapitalize : false
                    }, {
                        xtype: 'passwordfield',
                        name : 'password',
                        label: 'Clave',
                        useClearIcon: false
                    }]
                }],
                listeners : {
                    submit : function(form, result){
                        document.location = '/mobile/';
                    },
                    exception : function(form, result){
                        Ext.Msg.alert('Falla', result.msg, Ext.emptyFn);
                    }
                }


            };

            var dockedItems = [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                    {
                        text: 'Limpiar',
                        handler: function() {
                            form.reset();
                        }
                    },
                    {
                        text: 'Enviar',
                        ui: 'confirm',
                        handler: function() {
                            if(formBase.user){
                                form.updateRecord(formBase.user, true);
                            }
                            form.submit({
                                waitMsg : {
                                    message:'Enviando...',
                                    cls : 'demos-loading'
                                }
                            });
                        }
                    }
                    ]
                }
                ]

            panelcfg = {};
            panelcfg.dockedItems = dockedItems;

            if (Ext.is.Phone) {
                panelcfg.fullscreen = true;
            } else {
                Ext.apply(panelcfg, {
                    autoRender: true,
                    floating: true,
                    modal: true,
                    centered: true,
                    hideOnMaskTap: false,
                    height: 385,
                    width: 480
                });
            }
            form = new Ext.form.FormPanel(formBase);

            panelcfg.items = [
                {
                    bodyStyle: 'background-color: white',
                    height: 100,
                    html:'<center><img src="/images/logochico.jpg"/></center>'
                },
                form
            ];
            var panel = new Ext.Panel(panelcfg);


            panel.show();
        }
    });
</script>
    

<style type="text/css">
.demos-loading {
  background: rgba(0,0,0,.3) url(/js/sencha/resources/shared/loading.gif) center center no-repeat;
  display: block;
  width: 10em;
  height: 10em;
  position: absolute;
  top: 50%;
  left: 50%;
  margin-left: -5em;
  margin-top: -5em;
  -webkit-border-radius: .5em;
  color: #fff;
  text-shadow: #000 0 1px 1px;
  text-align: center;
  padding-top: 8em;
  font-weight: bold;
}
</style>
</head>
<body></body>
</html>
