/**
 * @package     Aplicacion
 * @subpackage  Default
 * @class       Model_DbTable_<?= $this->tableName ?>
 * @extends     Rad_Db_Table
 * @copyright   SmartSoftware Argentina
 */
class Model_DbTable_<?= $this->tableName ?> extends Rad_Db_Table
{
    protected $_name = '<?= $this->tableName ?>';

    protected $_referenceMap = array(
        <?= $this->references ?>
    );

    protected $_dependentTables = array(<?= $this->dependentTables ?>);
}