	    var dataClass= 'model/<?=$this->model?>/';
		
		var <?=$this->name?>store=new Ext.data.Store({
                    proxy: new Ext.data.HttpProxy({
                        url:  '<?=$this->controlerurl?>/list/'+ dataClass 
                    }),
					   remoteSort: true,
					   autoLoad: true,
	                reader: new Ext.data.JsonReader(
                        {root: 'rows'}
                       
                    )
				 });

        var <?=$this->name?> = new Ext.ux.RadGridPanel({
                    title:'Domaines',
      				id : "<?=$this->name?>Grid",
                    loadMask: true,
    		        deferredRender :false,
                    autoSave: true,
                    saveMetaUrl: '<?=$this->controlerurl?>/savemetadata/' + dataClass,
                    modifyUrl :  '<?=$this->controlerurl?>/savefield/'+ dataClass,
                    store : CMSstore ,
            	 	bbar: new Ext.PagingToolbar({
                        pageSize: 20,
                        store:  <?=$this->name?>store1,
                        displayInfo: true,
                        displayMsg: '{0} - {1} / {2}',
                        emptyMsg: "No hay registros",
    
            })
        });
