MyDesktop.<?=$this->name?> = Ext.extend(Ext.app.Module, {

	moduleType : 'app',
	moduleId : '<?=$this->name?>',
	
	init : function() {		
		this.launcher = {
			handler: this.createWindow,
			iconCls: 'notepad-icon',
			scope: this,
			shortcutIconCls: 'notepad-shortcut',
			text: 'Notepad',
			tooltip: '<b>Notepad</b><br />Jot down notes'
		};
	},

	createWindow : function() {
	var win = app.desktop.getWindow('<?=$this->name?>-win');

	if(!win) {
        var cfg = {
            title: '<?=$this->title?>',
            iconCls: 'notepad-icon',
            maximizable: <?= $this->maximizable?>,
            width: <?= $this->width?>,
            height: <?= $this->height?>,
            minWidth: <?= $this->minWidth?>,
            minHeight: <?= $this->minHeight?>,
            layout: 'fit',
            stateId: id,
            //items: <?=$this->windowExtContent?>,
            id: '<?=$this->name?>-win'
        };

	    win = app.desktop.createWindow(cfg);
	 }
        win.show();
    }
});