<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"; "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Rad Framework</title>
</head>
<body>
  <h1>Ocurrio un Error</h1>
  <h2><?= $this->message ?></h2>

  <? if (APPLICATION_ENV == 'development' || APPLICATION_ENV == 'testing'): ?>

  <h3>Information Excepcion:</h3>
  <p>
      <b>Message:</b> <?= ($this->exception) ? $this->exception->getMessage() : '' ?>
  </p>

  <h3>Traza:</h3>
  <pre><?= ($this->exception) ? $this->exception->getTraceAsString() : '' ?>
  <?php print_r($this->exception) ?>
  </pre>

  <h3>Parametros de la peticion:</h3>
  <pre><?= ($this->request) ? var_export($this->request->getParams(), true) : '' ?>
  </pre>
  <? endif ?>

</body>
</html>
