<?php echo $this->doctype();?>
<html>
<head>
    <link rel="shortcut icon" href="favicon.ico" >
    <link rel="icon" href="icon.gif" type="image/gif" >
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="author" />
    <style type="text/css">
        #ux-papelera-img {
            display:none;
        }
        #ux-papelera {
            overflow: visible;
            width:65px;
            height:65px ;
            padding: 15px;
            position: absolute;
            color: #ddd;
            bottom: 25px;
            right: 10px;
            cursor:default;
            z-index: 10;
        }
        #ss-softwareversion {
            position: absolute;
            color: #ddd;
            bottom: 5px;
            right: 10px;
            cursor:default;
            z-index: 10;
        }

        /* Animacion del loader */
        .loadinganim-ball {
            background-color: rgba(0,0,0,0);
            border:5px solid rgba(0,183,229,0.9);
            opacity:.9;
            border-top:5px solid rgba(0,0,0,0);
            border-left:5px solid rgba(0,0,0,0);
            border-radius:50px;
            box-shadow: 0 0 35px #2187e7;
            width:50px;
            height:50px;
            margin:0 auto;
            -moz-animation:spin .5s infinite linear;
            -webkit-animation:spin .5s infinite linear;
        }

        .loadinganim-ball1 {
            background-color: rgba(0,0,0,0);
            border:5px solid rgba(0,183,229,0.9);
            opacity:.9;
            border-top:5px solid rgba(0,0,0,0);
            border-left:5px solid rgba(0,0,0,0);
            border-radius:50px;
            box-shadow: 0 0 15px #2187e7;
            width:30px;
            height:30px;
            margin:0 auto;
            position:relative;
            top:-50px;
            -moz-animation:spinoff .5s infinite linear;
            -webkit-animation:spinoff .5s infinite linear;
        }

        @-moz-keyframes spin {
            0% { -moz-transform:rotate(0deg); }
            100% { -moz-transform:rotate(360deg); }
        }
        @-moz-keyframes spinoff {
            0% { -moz-transform:rotate(0deg); }
            100% { -moz-transform:rotate(-360deg); }
        }
        @-webkit-keyframes spin {
            0% { -webkit-transform:rotate(0deg); }
            100% { -webkit-transform:rotate(360deg); }
        }
        @-webkit-keyframes spinoff {
            0% { -webkit-transform:rotate(0deg); }
            100% { -webkit-transform:rotate(-360deg); }
        }
        .loadinganim-content {width:240px; margin:0 auto; padding-top:50px;}

        #loading{
            top:50%;
            left:50%;
            position: absolute;
            margin-left:-120px;
            margin-top:-190px;
            width:240px;
            height:125px;
            padding:2px;
            z-index:20001;
        }
        #loading a {
            color:#225588;
        }
        #loading .loading-indicator{
            -x-system-font:none;
            -webkit-border-radius: 20px;
            -moz-border-radius: 20px;
            border-radius: 20px;
            display:table-cell; vertical-align:middle;
            width:240px;
            height:125px;
            background:white;
            color:#444;
            font:bold 13px Helvetica, Arial, sans-serif;
            margin:0;
            padding:10px;
            text-align:center;
        }
        #loading-msg {
            margin-top: 108px;
            color: #017dc5;
            font-size: 14px;
            font-weight: normal;
        }
        /*#ux-taskbar {
            display: none;
        }*/
    </style>

    <link href="/js/ext/resources/css/ext-all.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="/js/ext/resources/css/xtheme-tp.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="/css/desktop.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="/css/custom.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="/css/RowEditor.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="/css/superboxselect.css" media="screen" rel="stylesheet" type="text/css" />

</head>
<body class="body <?=$this->classBody?>" style="<?php echo $this->fondo; ?>">
    <div id="loader" style="display:none;"></div>
    <?=$this->loading?>
    <?php if ($this->loading)  {  ?>
        <script type="text/javascript">document.getElementById('loading-msg').innerHTML = 'Cargando Core API...';</script>

    <?php
    } ?>

<?php
// Si esta en modo desarrollo cargamos el javascript de debug
if (APPLICATION_ENV == 'development') {
?>

    <script type="text/javascript" src="/js/ext/ext-base-debug.js"></script>
    <script type="text/javascript" src="/js/ext/ext-all-debug.js"></script>
<?php
} else {
?>

    <script type="text/javascript" src="/js/ext/ext-base.js"></script>
    <script type="text/javascript" src="/js/ext/ext-all.js"></script>

<?php
}
?>
    <script type="text/javascript" src="/js/ext/ext-lang-es.js"></script>
    <!--[if IE]>
    <style type="text/css">
    .x-form-field {vertical-align: baseline;}
    </style>
    <![endif]-->
    <?php if ($this->loading)  {  ?>
        <script type="text/javascript">document.getElementById('loading-msg').innerHTML = 'Cargando Componentes...'
        </script>
    <?php

    } ?>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript()?>
	<div id="x-desktop" class="x-unselectable">
	   <div id="ss-softwareversion" class="x-unselectable"><?php echo $this->version ?></div>
       <div id="ux-papelera" class="x-unselectable"><img id="ux-papelera-img" src="/images/papelera.png"/></div>
	</div>
    <div id="ux-taskbar">
		<div id="ux-taskbar-start"></div>
		<div id="ux-taskbar-panel-wrap">
			<div id="ux-quickstart-panel"></div>
			<div id="ux-taskbuttons-panel"></div>
			<div id="ux-tray-panel"></div>
		</div>
		<div class="x-clear"></div>
	</div>
</body>
</html>
