<?php
    //TODO: Reescribir esta chanchada (Martin)
    $section = ($this->iniSection == 'default') ? '' : $this->iniSection;
    $jsonExtFile = APPLICATION_PATH.'/modules/'.$this->moduleName.'/views/scripts/form/' . ($this->modelName) .$section. '.json';
    $isTemplate = file_exists($jsonExtFile);
    $layout = ($isTemplate || $this->itemsAdc) ? 'fit' : 'form';
?>
new <?= $this->extComponent ?>({
        labelWidth: 140,
        <?=$this->controlerurl?>
        <?=$this->fileUpload?>
        frame: true,
        bodyStyle:'padding:5px 5px 0',
        width: '100%',
        border: false,
        defaultType: 'textfield',
        layout: '<?= $layout ?>',

        <?php if (!$isTemplate): ?>
            buttons: [
                {
                    text: 'Guardar',
                    formBind: true,
                    handler: function () {this.findParentByType(<?= $this->extComponent ?>).submit()}
                }
            ],
        <?php endif; ?>
        
        items: [
            <?php
            if ($isTemplate) {
                echo $this->JsonRender($jsonExtFile, array_merge($this->items, $this->itemsAdc));
            }
            else {
                if ($this->itemsAdc) {
                    echo "{xtype:'panel', layout: 'border',items:[{xtype:'panel', region: 'center', layout: 'form', items:[";
                }
                $i = 0;
                foreach ($this->items as $k => $item)
                {
                    if ($i) echo ",";
                    $i++;
                    echo $item."\n"; 
                }
                if ($this->itemsAdc) {
                    echo "]},{xtype:'panel',height: 220, region: 'south',layout: 'fit', items: [";
                    foreach ($this->itemsAdc as $item) {
                        echo $item;
                    }
                    echo "]}]}";
                }
            }
?>
]})
