<script type="text/javascript">
 	Ext.onReady(function() {
 	 	Ext.get('loading').hide();
 	 	<?php
 	 	if ($this->path) {
 	 	?>
		Ext.Msg.getDialog().on('beforehide', function(){ document.location = '<?=$this->path?>'},this, {single:true});
		<?php
		
		}
		?>
        Ext.MessageBox.alert('Error', '<?=preg_replace("/\r?\n/", "\\n", addslashes($this->message))?>');
        
    },RADFramework);
</script>