<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html>
<head>
	<link rel="shortcut icon" href="favicon.ico" >
    <link rel="icon" href="animated_favicon.gif" type="image/gif" >
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="author" content="Martin Alejandro Santangelo" />
    <script type="text/javascript" src="/js/ext/ext-base.js.gz"></script>
    <script type="text/javascript" src="/js/ext/ext-all-debug.js.gz"></script>
    <script type="text/javascript" src="/js/ext/locale/ext-lang-es-min.js"></script>

    
    
    <link href="/js/ext/resources/css/ext-all.css" media="screen" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/js/ux/observableclass.js"></script>
<script type="text/javascript" src="/js/PubSub.js"></script>
<script type="text/javascript" src="/js/ux/menu/RangeMenu.js"></script>
<script type="text/javascript" src="/js/ux/menu/EditableItem.js"></script>
<script type="text/javascript" src="/js/ux/grid/CheckSelect.js"></script>
<script type="text/javascript" src="/js/ux/Ext.ux.autogrid.js"></script>

<script type="text/javascript" src="/js/ux/Ext.ux.RadForm.js"></script>
<script type="text/javascript" src="/js/ux/GridFilters.js"></script>
<script type="text/javascript" src="/js/ux/filters/Filter.js"></script>
<script type="text/javascript" src="/js/ux/filters/BooleanFilter.js"></script>
<script type="text/javascript" src="/js/ux/filters/DateFilter.js"></script>
<script type="text/javascript" src="/js/ux/filters/ListFilter.js"></script>
<script type="text/javascript" src="/js/ux/filters/StringFilter.js"></script>
<script type="text/javascript" src="/js/ux/filters/NumericFilter.js"></script>
<script type="text/javascript" src="/js/ux/form/xdatefield.js"></script>

<script type="text/javascript" src="/js/ux/form/datetime.js"></script>
<script type="text/javascript" src="/js/ux/form/xcombo.js"></script>
<script type="text/javascript" src="/js/ux/form/xcheckbox.js"></script>
<script type="text/javascript" src="/js/ux/form/maskfieldplugin.js"></script>
<script type="text/javascript" src="/js/ux/grid/GridSummary.js"></script>
<script type="text/javascript" src="/js/ux/renderers/basic.js"></script>
<script type="text/javascript" src="/js/ux/Ext.ux.IFrame.js"></script>
<script type="text/javascript" src="/js/ux/Ext.ux.RadMap.js"></script>
<script type="text/javascript" src="/js/ux/DragSelector.js"></script>

<script type="text/javascript" src="/js/ux/Ext.ux.RadChart.js"></script>
<script type="text/javascript" src="/js/ux/Ext.ux.form.LinkTriggerField.js"></script>
<body class="body">
    <div id="loader" style="display:none;"></div>
    
    <div id="loading">
      <div class="loading-indicator">
        <img src="/images/cargando.jpg" alt="Cargando..." /><br />

        <img src="/images/progress.gif" alt="Cargando..." />
      </div>
    </div>
</body>
</html>