MyDesktop.<?=$this->name?> = Ext.extend(Ext.app.Module, {
	
	moduleType: '<?=$this->moduleType?>',
	moduleId: 	'<?=$this->name?>',
	
	init : function() {
		this.launcher = {
			handler: this.createWindow,
			iconCls: '<?=$this->name?>-icon',
			scope: this,
			shortcutIconCls: '<?=$this->name?>-shortcut',
			text: '<?=$this->title?>',
			tooltip: '<?=$this->tooltip?>'
		};
	},
	
	createWindow: function() {
        var win = app.desktop.getWindow('<?=$this->name?>-win');
        if ( !win )
            win = this.create();
        win.show();
    },

    create: function() {
        return app.createWindow({
            id: '<?=$this->name?>-win',
            title: '<?=$this->title?>',
            width: 300,
            height: 250,
            iconCls: 'icon-grid',
            shim: false,
            animCollapse: false,
            layout: 'fit',
            items: [
                {
                    html: 'Sample App'
                }
            ]
        });
    }
});